# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	SYNC_FOLDER_HOST = "../../"
	SYNC_FOLDER_GUEST = "/vagrant"

	config.vm.box = "hashicorp/precise64"
	config.vm.synced_folder SYNC_FOLDER_HOST, SYNC_FOLDER_GUEST
	
	# Configuration for Ansible machine
	config.vm.define "ansible" do |ansible|
		ansible.vm.provision "shell", path: "./scripts/ansible_provision.sh"
		ansible.vm.network "private_network", ip: "192.168.0.10"	
	end
	
	# Configuration for Zookeeper machine
	config.vm.define "zookeeper" do |zookeeper|
		zookeeper.vm.provision "shell", path: "./scripts/change_mirrors.sh"
		zookeeper.vm.network "private_network", ip: "192.168.1.10"
		zookeeper.vm.synced_folder SYNC_FOLDER_HOST, SYNC_FOLDER_GUEST, disabled: true
	end
	
	# Configuration for first Kafka machine
	config.vm.define "kafka0" do |kafka0|
		kafka0.vm.provision "shell", path: "./scripts/change_mirrors.sh"
		kafka0.vm.network "private_network", ip: "192.168.2.10"
		kafka0.vm.synced_folder SYNC_FOLDER_HOST, SYNC_FOLDER_GUEST, disabled: true
	end

	# Configuration for second Kafka machine
	config.vm.define "kafka1" do |kafka1|
		kafka1.vm.provision "shell", path: "./scripts/change_mirrors.sh"
		kafka1.vm.network "private_network", ip: "192.168.2.11"
		kafka1.vm.synced_folder SYNC_FOLDER_HOST, SYNC_FOLDER_GUEST, disabled: true
	end

end
